### ISSUE TITLE
Getting a 404 error

### ISSUE THREAD

**Issue by deanpribetic** [savdagod/TidbytAssistant#13]
Hi there! Trying to deploy TidbyAssistant and am getting…

`Failed to perform the action tidbytassistant.text. 404 page not found`

When trying to do anything. My setup is:

- TidbytAssistant add-on running on port 24086
- TidbytAssistant integration configured as:

```
tidbytassistant:
  host: 192.168.4.55
  port: 24086
  device:
    - deviceid: !secret tidbyt_id
      token: !secret tidbyt_key
```

192.168.4.55 is the IP address of my HomeAssistant box

![CleanShot 2024-10-28 at 16 54 27](https://github.com/user-attachments/assets/fa91d0e8-9765-49f7-af4f-30b7af3fb05a)
