### ISSUE TITLE
Support using docker (not hassio addon)

### ISSUE THREAD

**Issue by addd45** [savdagod/TidbytAssistant#19]
Hi there and thanks for making this integration, I'm excited to get using it. 

So I am trying to use this addon with just docker and not the hassio addon, which the docs say is possible. However, there isn't really any documentation on how to do this, and I am getting a peculiar error that hints that the integration is expecting hassio.

Here is my config
```
tidbytassistant:
  port: 8900
  external_addon: true
  device:
    - 
      #name: your device name #this is optional now, as the integration will get the device name using the Tidbyt API
      deviceid: !secret my_device_id
      token: !secret tidbyt_token
```

Here is the error log - 
```
Logger: homeassistant.setup
Source: setup.py:269
First occurred: 9:00:09 PM (2 occurrences)
Last logged: 9:00:10 PM

Setup failed for 'hassio': Integration failed to initialize.
Setup failed for custom integration 'tidbytassistant': Could not setup dependencies: hassio
```

also side note, I had to change my port, which also required me to change `main.go` and a couple other config files. Ideally this would all come from a single env, but I understand this likely a low priority.
