### ISSUE TITLE
No device name selectable

### ISSUE THREAD

**Issue by sirtakahe** [savdagod/TidbytAssistant#23]
My home assistant notifications that use TidbytAssistant: Text and TidbytAssitant: Push are no longer showing a selectable Tidbyt/Tronbyt device.

However my buttons for pushing preconfigured text messages to any on my Tidybyt/Tronbyt devices to test end to end communications between HA and Tronbyt Server are still working, so this indicates that my configuration.yaml file has the correct device IDs, keys etc.

TidybytAssistant Version downloaded: d5d1Fd1
Addon version: 1.0.16

Tried re-downloading and rebooting HA.

Thanks.

<img width="839" alt="Image" src="https://github.com/user-attachments/assets/add33f5a-1720-4a0d-b066-9b0b9bdaa4ef" />

**Comment by IngmarStein** [comment]
Looking at the code a bit more, are your devices in `custom_components/tidbytassistant/services.yaml`? The integration writes that file at setup time based on the active configuration at that time. I'm wondering when that lifecycle function is called.

**Comment by sirtakahe** [comment]
Hi there

Devices are in configuration.yaml as follows:

tidbytassistant:
  device:
    - name: Tronbyt 1
      deviceid: a19a1217
      token: xxxxxxxx
      apiurl: http://192.168.1.39:8000
      
    - name: Takahe
      #host: 192.168.1.30
      deviceid: differently-pliable-flashy-rhea-ca6
      token: xxxxxxxx


I haven’t got them defined in services.yaml, never had to date, has the code changed to now require them set here as well?

Text push from a notification seems to have stopped working (I.e. devices no longer seen in the notification configuration) a couple of core versions ago, was fine a couple of weeks ago.

Section of services.yaml that calls device name:

    devicename:
      name: Device Name
      description: The Tidbyt device you want content to be displayed to.
      required: true
      selector:
        select:
          multiple: true
          options: *id001

**Comment by IngmarStein** [comment]
Your config looks good.

There should be no need to modify `services.yaml` manually, the integration does that at setup time.
If successful, it looks like this:

```
    devicename:                                                                           
      name: Device Name                                                                   
      description: The Tidbyt device you want content to be displayed to.                 
      required: true                                                                      
      selector:                                                                           
        select:                                                                           
          multiple: true                                                                  
          options: &id001                                                                 
          - label: Living Room                                                            
            value: Living Room                                                            
          - label: Office                                                                 
            value: Office                                                                 
          - label: Loft                                                                   
            value: Loft                                                                   
```

You can try that and restart and see if it helps.
