### ISSUE TITLE
Card to Type text to Send to TIDBYT

### ISSUE THREAD

**Issue by roomonthethird** [savdagod/TidbytAssistant#3]
Hello!

Made a quick card that allows you to send any text to the TIDBYT using [notify-card](https://github.com/bernikr/lovelace-notify-card):

```
type: custom:notify-card
label: Enter text
card_title: Send a Message!
notification_title: null
action: tidbytassistant.text
data:
  message: $MSG
  font: tb-8
  color: '#fff'
  content: $MSG
  texttype: scrolling
  devicename: your device name
```

I'm still new to HA, so if anyone knows how to make it so there are drop downs for selecting text, color and type, that would be sick!
